# Site settings
title: How is Daniel
email: dan.m.bartel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  How is Daniel doing?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://howisdaniel.github.io" # the base hostname & protocol for your site
twitter_username: helloimdanielhi
github_username:  dbartel

# Build settings
markdown: kramdown
